# Generated by Django 2.2.2 on 2020-03-26 13:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TempAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=50)),
                ('firstname', models.CharField(default='', max_length=50)),
                ('lastname', models.CharField(default='', max_length=50)),
                ('email', models.EmailField(default='', max_length=50)),
                ('mobile', models.CharField(default='', max_length=10)),
                ('password', models.CharField(blank=True, max_length=50, null=True)),
                ('state', models.CharField(default='', max_length=50)),
                ('city', models.CharField(default='', max_length=50)),
                ('pincode', models.CharField(default='', max_length=6)),
                ('area', models.CharField(default='', max_length=50)),
                ('address', models.TextField()),
                ('category', models.CharField(default='customer', max_length=20)),
                ('otp', models.CharField(max_length=10)),
                ('expire', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=50)),
                ('firstname', models.CharField(default='', max_length=50)),
                ('lastname', models.CharField(default='', max_length=50)),
                ('email', models.EmailField(default='', max_length=50)),
                ('mobile', models.CharField(default='', max_length=10)),
                ('state', models.CharField(default='', max_length=50)),
                ('city', models.CharField(default='', max_length=50)),
                ('pincode', models.CharField(default='', max_length=6)),
                ('area', models.CharField(default='', max_length=50)),
                ('address', models.TextField()),
                ('category', models.CharField(default='customer', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
