# Generated by Django 2.2.2 on 2020-03-30 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='kart',
            new_name='cart',
        ),
    ]
